const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const LOGIN_FAILED = 'LOGIN_FAILED'

const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
const SIGNUP_FAILED = 'SIGNUP_FAILED'

const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS'
const USER_LOADED_FAILED = 'USER_LOADED_FAILED'

export { LOGIN_SUCCESS, LOGIN_FAILED, SIGNUP_SUCCESS, SIGNUP_FAILED, USER_LOADED_SUCCESS, USER_LOADED_FAILED }