# Generated by Django 3.2.5 on 2021-07-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costumer',
        ),
    ]
