# Generated by Django 3.2.5 on 2021-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecom', '0002_delete_costumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('is_digital', models.BooleanField()),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
