# Generated by Django 3.2.5 on 2021-08-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_costumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='name',
        ),
    ]
