# Generated by Django 3.2.5 on 2021-11-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_auto_20210809_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
