# Generated by Django 3.2.5 on 2021-11-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0005_alter_costumer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.EmailField(blank=True, default='blank@gmail.com', max_length=255, null=True),
        ),
    ]
